language: java
sudo: false

jdk:
  - oraclejdk7

script:
  - ./travis.sh

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sonar

notifications:
  email: false
  webhooks:
    - secure: "e6/3Wlr9+ArBpoy+FCwXJ3hJEnHQBe5bnfWyg60SNwqDjJj2TsSQvz2dpp/PCU4sRnf0bzlML+WZ5u7ZsW+qRFMSVu+s5flhdHCNm6cIPwTvikqdXDGquP7GMMsyYlfDyAmgpkeowg3Z2fbgAtOG1ENQIH6eM294skQvAb73yp4="
